name: LocateCities
version: 1.2.0
main: it.samuconfaa.locateCities.LocateCities
author: SamuConfaa
description: Plugin per localizzare città del mondo reale in coordinate Minecraft con sistema avanzato di cooldown
api-version: 1.21
website: https://github.com/samuconfaa/LocateCities
depend: [Vault]
softdepend: [Vault]

commands:
  citta:
    description: Comandi per interagire con le città
    usage: /<command> <search|tp|history|tutorial> [parametri]
    permission: locatecities.use
    permission-message: Non hai il permesso per usare questo comando
    aliases: [city, locate]
  cittaadmin:
    description: Comandi amministrativi per LocateCities
    usage: /<command> <reload|clearcache|info|setorigin|setscale|stats|near|bypass|playerhistory|cleandb|dbstats>
    permission: locatecities.admin
    permission-message: Non hai il permesso per usare questo comando

permissions:
  locatecities.use:
    description: Permette di usare i comandi /citta
    default: true
  locatecities.teleport:
    description: Permette di teletrasportarsi alle città
    default: true
  locatecities.admin:
    description: Permette di usare i comandi amministrativi
    default: op
  locatecities.free:
    description: Bypass di tutti i costi economici e cooldown
    default: op
  locatecities.noratelimit:
    description: Bypass del rate limiting per secondo
    default: op